[#12] Validate powershell
Introduce a new job for running PSScriptAnalyzer in the GitHub Actions
workflow. Install the necessary module and check for script issues,
outputting results in a markdown table. Ensure the build fails if any
errors are found in the PowerShell scripts.

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -1,4 +1,4 @@
-name: validate-SVG
+name: Validate
 on: push
 
 permissions:
@@ -6,7 +6,51 @@ permissions:
   pull-requests: write
 
 jobs:
-  validate-linter:
+  powershell-linter:
+    name: Run Powershell Linter
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install PSScriptAnalyzer module
+        shell: pwsh
+        run: |
+          Set-PSRepository PSGallery -InstallationPolicy Trusted
+          Install-Module PSScriptAnalyzer -ErrorAction Stop
+      - name: Lint with PSScriptAnalyzer
+        shell: pwsh
+        run: |
+          Invoke-ScriptAnalyzer -Path *.ps1 -Recurse -Outvariable issues
+          $errors   = $issues.Where({$_.Severity -eq 'Error'})
+          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
+          if ($errors) {
+              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total."
+          } else {
+              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
+          }
+
+            if ($issues) {
+              # Format issues into a markdown table
+              $markdownTable = ""
+              $markdownTable += "| Severity | RuleName | ScriptName | Line | Message |`n"
+              $markdownTable += "|----------|----------|------------|------|---------|`n"
+
+              foreach ($issue in $issues) {
+                $markdownTable += "| $($issue.Severity) |$($issue.RuleName) | $($issue.ScriptName) |$($issue.Line) | $($issue.Message) |`n"
+              }
+
+              # Output the markdown table to the step summary
+              $markdownTable | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            }
+
+          # Fail the build if there are any errors in the script files
+          if ($errors) {
+              Write-Error "Errors found in script files."
+              exit 1
+          } else {
+              Write-Output "No errors found in script files."
+          }
+
+  svg-linter:
     name: Run SVG Linter
     runs-on: ubuntu-latest
     steps:
